- robot: herb
  kinbody: bowl
  action: grasp
  sample_goal: True
  TSRs:
     - Tw_e: [[1., 0., 0., 0.08], [0., -1., 0., 0.], [0., 0., -1., 0.27], [0., 0., 0., 1.]]
       Bw: [[ 0., 0. ], [0., 0.], [0., 0.], [0., 0.], [0., 0.], [-3.14, 3.14]]